name: REAL_test_nginx 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    # - name: set NOW
    #   run: |
    #       echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')"
    
    - name: Get the datetime string
      # You may pin to the exact commit or the version.
      # uses: ccccmagicboy/get_datetime@90837a2b6b95a8eeb840284775958b1528614eec
      uses: ccccmagicboy/get_datetime@v0.1
      with:
        # time zone of the datetime
        tz1: Asia
        # time zone of the datetime
        tz2: Seoul

    - name: Build the Docker image
      uses: actions/checkout@v3

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
          images: swsw1005/test_nginx
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}-${{env.NOW}}
          labels: ${{ steps.docker_meta.outputs.labels }}
    
      # run: docker build . --file Dockerfile --tag swim_nginx_test:$(date +%s)
