name: REAL_test_nginx 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    # - name: set NOW
    #   run: |
    #       echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')"

    # echo ::set-output name=datetime_str::20231112_161856_KST+0900

    - name: Set output
      id: datetime_gen
      run: echo "NOW=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      uses: actions/checkout@v3

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
          images: swsw1005/test_nginx
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}-${{ steps.datetime_gen.outputs.NOW }}
          labels: ${{ steps.docker_meta.outputs.labels }}
    
      # run: docker build . --file Dockerfile --tag swim_nginx_test:$(date +%s)
